### ISSUE TITLE
ssh_config support for Include keywords

### ISSUE THREAD

**Issue by cordula-grau** [fitztrev/shuttle#229] opened 2018-04-12 07:35 UTC
Shuttle does not display any hosts of my ~/.ssh/config because there are only files included with the "Include" keyword. Would it be possible to add the feature to resolve files referenced by this keyword?

`Include the specified configuration file(s).  Multiple pathnames may be specified and each pathname may contain glob(3) wildcards and, for user configurations, shell-like '~' references to user home directories.  Files without absolute paths are assumed to be in ~/.ssh if included in a user configuration file or /etc/ssh if included from the system configuration file.  Include directive may appear inside a Match or Host block to perform conditional inclusion.`

**Comment by thshdw** [comment] 2018-06-19 16:28
This seems to be a duplicate of #162 if not please let me know

**Closed by thshdw** 2018-06-19 16:28 UTC
Labels: duplicate

**Comment by cordula-grau** [comment] 2018-06-19 17:05
No, #162 us about multiple ssh_config files. What I mean is the native ssh_config keyword „Include“ which can be used inside the ssh_config file and is just ignored by Shuttle.

**Comment by thshdw** [comment] 2018-06-19 17:14
@cordula-grau See the comment from @otherguy 
> Starting with ssh 7.3 (released on August 1st, 2016), an Include directive is available in ssh config files.

I could change the title in #162 so that its clear

**Comment by cordula-grau** [comment] 2018-06-19 17:19
Okay, I am fine

**Comment by thshdw** [comment] 2018-06-19 17:21
Okay #162 has been renamed 
>Parse multiple ssh_config files using the new Include directive

**Comment by julien-c** [comment] 2018-08-15 10:59
@cordula-grau Just merged #238 in, let me know if it works for you.

**Comment by cordula-grau** [comment] 2018-12-05 07:40
@julien-c basic include works, but globs do not like
`Include include.d/*`

**Comment by zatnekitel** [comment] 2019-08-31 21:57
> @julien-c basic include works, but globs do not like
> `Include include.d/*`

It will be nice to support wildcards creating a new submenu per-file included.
