### ISSUE TITLE
If no iTerm2 is open, the command won't run

### ISSUE THREAD

**Issue by FezVrasta** [fitztrev/shuttle#155] opened 2015-12-16 11:26 UTC
If I use Shuttle to run a command when iTerm2 is not yet open, iTerm2 will be opened and closed instantly and nothing else will happen.

Am I doing something wrong?

**Comment by thshdw** [comment] 2015-12-16 14:01
In your JSON config are you specifying the version
```
"iTerm_version": "VALUE",
```
Possible values are ```stable``` or ```nightly```

**Comment by FezVrasta** [comment] 2015-12-16 14:04
no I'm not specifying anything.

If I set it to nightly (I'm on 2.9) the bug is still there, if I set it to stable, after the behavior I've described, a new (empty) terminal is opened.

**Comment by thshdw** [comment] 2015-12-16 14:09
With iTerm you have to set ```"iTerm_version": "VALUE",``` in your case it would be ```nightly```
This behavior can also occur if your passing the wrong theme / profile. In your iTerm settings is your default profile ```Default```

**Comment by FezVrasta** [comment] 2015-12-16 14:11
I've not configured any profile or theme. If I set to nightly, the problem described in this issue is still there.

**Comment by thshdw** [comment] 2015-12-16 14:14
What shuttle version are you using? I just download the latest iTerm nightly and with shuttle version 1.2.5   iTerm opens my commands as expected.

**Comment by FezVrasta** [comment] 2015-12-16 14:18
I'm on 1.2.5 as well.

This is my configuration:

```
{
	"_comments": [
		"Valid terminals include: 'Terminal.app' or 'iTerm'",
		"Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
		"For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
	],
	"terminal": "iTerm",
	"iTerm_version": "nightly",
	"launch_at_login": true,
	"show_ssh_config_hosts": true,
	"ssh_config_ignore_hosts": [],
	"ssh_config_ignore_keywords": [],
	"hosts": [
		{
			"Test": [
				{
					"name": "app-staging2 dev",
					"cmd": "itermocil app-staging2-dev; open http://localhost:8001; exit"
				}
			]
		}
	]
}
```

**Comment by thshdw** [comment] 2015-12-16 14:19
testing...

**Comment by thshdw** [comment] 2015-12-16 14:29
It appears to work for me. iTerm opens the command is inputted; my browser opens localhost. This is with iTerm completely closed. 

<img width="586" alt="screen shot 2015-12-16 at 7 23 41 am" src="https://cloud.githubusercontent.com/assets/4992951/11843392/9949196c-a3c6-11e5-94b0-9c7d91d5d574.png">

At the end of your command you have ```exit``` this will cause iTerm to close.

**Comment by FezVrasta** [comment] 2015-12-16 14:32
No, even without `exit` it happens the same. (I've `exit` because `itermocil` will open a new tab of iterm for me)

**Comment by thshdw** [comment] 2015-12-16 14:34
if your change your command to ```ps aux | grep foo``` does that work?

**Comment by FezVrasta** [comment] 2015-12-16 14:37
no, same problem with every command I've tried so far

**Comment by thshdw** [comment] 2015-12-16 14:40
Do you have both iTerm stable and iTerm nightly installed?

**Comment by FezVrasta** [comment] 2015-12-16 14:40
No, just iTerm nightly :(

**Comment by thshdw** [comment] 2015-12-16 14:48
try this config
```
{
  "editor": "default",
  "launch_at_login": false,
  "terminal": "iTerm",
  "iTerm_version": "nightly",
  "default_theme": "Default",
  "open_in": "tab",
  "show_ssh_config_hosts": false,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "title": "test",
      "name": "Grep - Opens in Default-window-theme-title"
    }
  ]
}
```

**Comment by FezVrasta** [comment] 2015-12-16 14:53
Even with that config the terminal automatically close after few ms

**Comment by thshdw** [comment] 2015-12-16 15:01
This seems like some conflicts with having iTerm stable installed at one time.

* Remove iTerm from applications. Search your system for iTerm maybe the app is in other folders remove all instances of the app.
* Remove iTerm and iTerm2 from ~/Library/Application Support
* Remove ~/Library/Preferences/com.googlecode.iterm2.plist
* Download a fresh Nightly https://iterm2.com/downloads/nightly/#/section/home
* Open iTerm one time and go to the preferences area.

**Comment by jk2K** [comment] 2015-12-17 09:36
I  also met the problem， I follow your steps, but still won't run, I just installed iTerm nightly

my iTerm2 version: Build 2.9.20151213-nightly

**Comment by thshdw** [comment] 2015-12-17 09:40
Is it the same with every command? If your command is something basic like "ps aux | grep foo" do you have the same issue?

Sent from Outlook Mobile




On Thu, Dec 17, 2015 at 1:36 AM -0800, "Meng Ye" <notifications@github.com> wrote:












I  also met the problem， I follow your steps, but still won't run, I just installed iTerm nightly



my iTerm2 version: Build 2.9.20151213-nightly

**Comment by jk2K** [comment] 2015-12-17 09:56
my shuttle work properly now, my config like this
```config
"hosts": [
        {
            "demo": [
                {
                    "cmd": "ssh test@XXXXXX",
                    "name": "test 2",
                    "title": "title of tab"
                },
                {
                    "cmd": "ssh test@XXXXX",
                    "inTerminal": "tab",
                    "name": "test 1",
                    "theme": "default",
                    "title": "title of tab"
                }
         }
]
```
` "theme": "default"` should be ` "theme": "Default"`

Many thanks

**Comment by thshdw** [comment] 2015-12-17 09:59
Thanks for the update!

Sent from Outlook Mobile




On Thu, Dec 17, 2015 at 1:56 AM -0800, "Meng Ye" <notifications@github.com> wrote:












my shuttle work properly now, my config like this

"hosts": [
        {
            "demo": [
                {
                    "cmd": "ssh test@XXXXXX",
                    "name": "test 2",
                    "title": "title of tab"
                },
                {
                    "cmd": "ssh test@XXXXX",
                    "inTerminal": "tab",
                    "name": "test 1",
                    "theme": "default",
                    "title": "title of tab"
                }
         }
]




"theme": "default" should be "theme": "Default"



Many thanks

**Comment by FezVrasta** [comment] 2015-12-17 11:57
Same problem even after your advices

**Comment by thshdw** [comment] 2015-12-17 15:03
Sorry it's not working for you Fez. Tomorrow I'll send you the sandbox version to see if that helps.

Sent from Outlook Mobile




On Thu, Dec 17, 2015 at 3:57 AM -0800, "Fez Vrasta" <notifications@github.com> wrote:












Same problem even after your advices

**Comment by kiahhan** [comment] 2015-12-22 00:25
I met the same problem, still not work after I try your advice configuration.

**Comment by thshdw** [comment] 2015-12-22 00:29
In Applications is the spelling of iTerm; iTerm or iTerm2 or iTerm-2 or something else?

Sent from Outlook Mobile




On Mon, Dec 21, 2015 at 4:24 PM -0800, "Kiah Han" <notifications@github.com> wrote:












I met the same problem, still not work after I try your advice configuration.

**Comment by FezVrasta** [comment] 2015-12-22 09:40
I'm still waiting for the sandbox version, please.

**Comment by thshdw** [comment] 2015-12-29 22:49
@FezVrasta Thanks for your patience. Attached is my sandbox build, please note that is a test debug version. not for release. Please test and let me know if the issue is resolved. 

[Shuttle.zip](https://github.com/fitztrev/shuttle/files/74441/Shuttle.zip)

**Comment by thshdw** [comment] 2016-02-24 09:31
fixed in release v.1.2.6 pull #165

**Closed by thshdw** 2016-02-24 09:31 UTC
Labels: Complete
