### ISSUE TITLE
terminal window flickers when opening iTerm2 window

### ISSUE THREAD

**Issue by PaulDapolito** [fitztrev/shuttle#168] opened 2016-04-25 04:14 UTC
I am running Shuttle v1.2.6 on Mac OS X 10.11.4 under the following `.shuttle.json` configuration (as an example):
```
{
  "editor": "default",
  "launch_at_login": true,
  "terminal": "iTerm",
  "iTerm_version": "stable",
  "default_theme": "Default",
  "open_in": "tab",  
  "show_ssh_config_hosts": false,
  "hosts": [
    {
      "cmd": "ssh test@test.com",
      "inTerminal": "tab",
      "name": "Local",
      "title": "Local"
    },
  ]
}
```

When I click any of the hosts listed in Shuttle dropdown menu, I see the following visual flickering:
![Possible bug in fitztrev/shuttle](http://i.imgur.com/wm9ldv3.gif)

Does anyone else experience this issue? Thanks very much for any insight.

**Comment by thshdw** [comment] 2016-04-25 20:18
Hello @PaulDapolito this is by design. A window is getting opened and then we are closing it. This is why the title says "2.Local"..

Here is the [applescript](https://github.com/fitztrev/shuttle/blob/7d317a76c6bc6edccb3ce406fbbcde5effb87334/apple-scripts/iTermStable/iTerm-stable-new-tab-default.applescript#L48) that is doing this....

```
			--iTerm is running get the window count
			set windowCount to (count every window)
			set curTerm to (current terminal)
			if windowCount = 0 then
				--app is running with no windows
				--reopen opens iTerm using default settings
				reopen
				--we dont want the defaults.
				--lets close this and make our own
				terminate the first session of the first terminal
				set newTerm to (make new terminal)
				tell newTerm
					set newSession to (launch session withTheme)
					tell newSession
						write text withCmd
						set name to theTitle
						activate
					end tell
				end tell
			else
```
Explanation: 
iTerm is running but we don't have any windows open, so in this case when a command is sent to iTerm. iTerm will open a window with its own default settings. However we want to define the options using shuttle and the rules we send through the json file. So we have to terminate the default window and make a new one. This new window contains the settings and directives specified in our json file. 

The flicker you are seeing is ```terminate the first session of the first terminal```

If you keep 2.local open and run another command you wont see the flicker because a window is already open. 

Also see https://github.com/fitztrev/shuttle/commit/924561b88046bbed421dcd808658b099eb4208d5 and https://github.com/fitztrev/shuttle/pull/158 and https://github.com/fitztrev/shuttle/issues/143

**Comment by thshdw** [comment] 2016-05-03 18:44
I think that this is resolved... if not please reopen 😄

**Closed by thshdw** 2016-05-03 18:44 UTC
