### ISSUE TITLE
iTerm2 with new window settings does not open in a new window.

### ISSUE THREAD

**Issue by h-code** [fitztrev/shuttle#132] opened 2015-10-16 07:42 UTC
new release 1.2.3 does not open window on iTerm2

**Comment by h-code** [comment] 2015-10-16 07:48
it's the same with terminal
with or without the inTerminal parameter
(running OS X El Capitan)

**Comment by thshdw** [comment] 2015-10-16 16:01
What version of iTerm are you using? 
Sorry about that. I tested using iTerm nightly, its working on my dev Mac. I just tried it on another and its not working.

**Comment by h-code** [comment] 2015-10-16 16:05
2.1.4.. This is the last available release when I check for update
Would you like me to activate any debug ?

**Comment by thshdw** [comment] 2015-10-16 16:09
@h-code Thanks for letting me know what version you are using.... in the settings area of your JSON make sure that you have ```  "iTerm_version": "stable",```
If that is missing iTerm wont open. Check then test again for me!  Thanks!

**Comment by h-code** [comment] 2015-10-16 16:17
it work with iTerm_version settings !
Thanks :-)

"inTerminal":"new"  does not work. Should I move to iTerm nightly build  ?

**Comment by thshdw** [comment] 2015-10-16 16:25
You're Welcome!
it seems I have bug with ```inTerminal":"new"``` 
Moving to iTerm nightly is entirely up to you. We are adding support for both Stable and Nightly because of the apple script changes between the two are very different. If your happy with Stable keep using it :smile:

**Comment by h-code** [comment] 2015-10-16 16:28
so I will keep it "stable"

**Comment by thshdw** [comment] 2015-10-17 00:09
@h-code I have fixed the bug to ```"inTerminal":"new"``` for iTerm nightly. Stable is working for me with no changes. Could test ```"inTerminal":"new"``` and ```"inTerminal":"current" for me 

```
    {
      "cmd": "ps aux | grep new",
      "inTerminal": "new",
      "name": "Test-Open in new Term window"
    },
```

```
    {
      "cmd": "ps aux | grep current",
      "inTerminal": "current",
      "name": "Test-Open in current terminal"
    },
```

**Comment by thshdw** [comment] 2015-10-18 06:38
I think this issue is resolved. Please reopen if this is not the case

**Closed by thshdw** 2015-10-18 06:38 UTC
Labels: Complete

**Comment by h-code** [comment] 2015-10-19 07:20
I thought "inTerminal" was global setting. 
Actually it is working, if I set it at the command level. :-)

Don't you think it could be helpful to have it at the global level ?

**Comment by thshdw** [comment] 2015-10-19 16:16
@h-code I did think about having it at the Global level. With this change you have two new options...

```"inTerminal":"new"``` will open the command in a new Terminal. 
```"inTerminal":"current"``` will open the command in the current active terminal window. This one is useful if you want to run a regular used command or script on your remote system. So if you are ssh'd to a system the command will run in this remote server. 
 
I think its more flexible at the command level. The default action is to have all commands open in new tabs. But maybe the user wants only some commands to open in new windows. Surely users would not want all commands to open in current terminals. 

I could see why users would want all commands to open in New terminals, I would be open to a new Global setting that would do this. 

If a Global setting existed that allowed you open all commands in new terminal windows; would you want the command level ```inTerminal``` override the Global settings or would you want the Global settings so override the command settings.

**Comment by thshdw** [comment] 2015-10-19 16:53
@h-code I was thinking about this a bit... What we would really be doing is changing the default behavior. So the command level ```inTerminal``` would override whatever you set as the default. 

So maybe the global setting should be: 
```"Terminal_Open":"tabs"``` Always opens in a new tab, unless you have an ```inTerminal``` directive
```"Terminal_Open":"windows"``` Always opens in a new window, unless you have an ```inTerminal``` directive

If ```Terminal_Open``` is missing then it defaults to opening in a new tab.

**Comment by h-code** [comment] 2015-10-19 16:55
@thshdw  It looks good !

**Comment by philippetev** [comment] 2015-10-29 20:29
Shuttle 1.2.4, iTerm2 2.1.4, El Capitan 10.11.1 
I'm using the following config:

{
	"editor": "default",
	"show_ssh_config_hosts": false,
	"launch_at_login" :false,
	"iTerm_version": "stable",
	"ssh_config_ignore_hosts": [],
	"ssh_config_ignore_keywords": [],
	"terminal": "iTerm",
	"hosts":[
		{"cmd": "ssh root@192.168.0.2 -i ~/MyKey09052012_private.openssh",
			"inTerminal": "new",
			"theme": "Default",
			"name": "NAS"
		}]
}

With inTerminal, set to "new", iTerm is opening for a second and then closes immediately.
What have I missed?

**Comment by thshdw** [comment] 2015-10-29 22:40
@philippetev ```"iTerm_version": "stable",``` is set in your settings make sure you have iTerm 2.1.4 only and that you have the most recent version... Stable was updated recently. Please get the latest stable from the iTerm website and try again

If you have iTerm Stable installed and you also have iTerm Nightly installed it wont work. You cant have both versions installed. If you have both iTerm Stable and some other version of iTerm do the following:

* Remove iTerm 2 from applications. Search your system for iTerm maybe the app is in other folders. 
* Remove iTerm and iTerm2 from ~/Library/Application Support 
* Download a fresh Stable https://iterm2.com/downloads/stable/iTerm2-2_1_4.zip this fresh version has updates for 10.11
* Open iTerm one time and go to the preferences area.

**Comment by philippetev** [comment] 2015-10-30 06:31
That's not the place where iTerm keeps its settings, but your proposition gave me a tip. Deleted the iTerm config file com.googlecode.iterm2.plist from ~/Library/Preferences and setup the iTerm from scratch. Now, with inTerminal, set to "new", the iTerm starts normally, but on already started iTerm it keeps creating new iTerm windows instead of tabs. Is that "by design"?

**Comment by thshdw** [comment] 2015-10-30 15:45
@philippetev Thanks for the tip!
```"inTerminal": "new",``` will always open the command in a new terminal window. I'm working on a revised readme.md with a full set of directives... you can see the [draft here.](https://github.com/thshdw/shuttle/blob/fix-editor-settings/README.md) Keep in mind that some of the sttings in this draft are for the v1.2.5 which has not yet been released.

**Comment by anilbattini** [comment] 2019-03-06 10:04
for iterm2, open preferences -> advanced tab -> in the search bar type "new window" -> under windows section, change  'open files in new windows, not new tabs' to 'yes'. Default is 'no'.
