### ISSUE TITLE
No longer works with iTerm2 (3.0.0)

### ISSUE THREAD

**Issue by cmgmyr** [fitztrev/shuttle#174] opened 2016-06-01 18:13 UTC
I've also tried updating the config to use: `"iTerm_version": "nightly",` and `"iTerm_version": "stable",` as well as removing it. I haven't been able to get it to work

**Comment by daften** [comment] 2016-06-01 18:29
I have the same problem ATM

**Comment by skebi69** [comment] 2016-06-01 18:35
Ditto. There is no output at all.

**Comment by kandrei** [comment] 2016-06-01 19:22
Same for me. Updated to iTerm2 3.0.0 and Shuttle doesn't open terminals anymore. If Iterm is closed, it opens and then quickly closes. If it's already open, it doesn't do anything.

**Comment by killerwolf** [comment] 2016-06-02 07:57
Same problem here, switched back to Terminal.app for now

**Comment by Dreeg** [comment] 2016-06-02 09:38
Me too.

**Comment by berkayunal** [comment] 2016-06-02 12:19
Same here :(

**Comment by patroqueeet** [comment] 2016-06-02 14:13
+1

**Comment by isaiasneto** [comment] 2016-06-02 14:59
+1

**Comment by rodaddy** [comment] 2016-06-02 16:57
ditto

**Comment by rodaddy** [comment] 2016-06-02 17:01
just changed my JSON, and now it works.
"editor": "default",
  "launch_at_login": true,
  "terminal": "iTerm",
  "iTerm_version": **"nightly",**
  "default_theme": "Man Page",
  "open_in": **"tab"**,  
  "show_ssh_config_hosts": true,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "hosts":

**Comment by kandrei** [comment] 2016-06-02 17:37
Confirmed, the @rodaddy changes to the config file work.

**Comment by skebi69** [comment] 2016-06-02 18:00
Hmmm. The change did not work for me.

  "editor": "vim",
  "launch_at_login": true,
  "terminal": "iTerm",
  "iTerm_version": "nightly",
  "open_in": "tab",
  "default_theme": "Default",
  "show_ssh_config_hosts": true,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],

**Comment by kandrei** [comment] 2016-06-02 18:05
My only set of parameters that have anything to do with iTerm are:

"terminal": "iTerm",
"iTerm_version": "nightly",
"open_in": "tab",
"launch_at_login": true,

The differences from before the upgrade are the "iTerm_version" parameter which was changed to "nightly" and the addition (I didn't have it previously) of the "open_in" parameter with the value "tab".

Maybe you could try only with these, without default_theme and editor.

I've tested again and it still works ;) It works with iTerm closed and it also works with iTerm already open. **Shuttle version 1.2.5.**

**Comment by skebi69** [comment] 2016-06-02 18:11
I am on 1.2.6. I took out the editor and default_theme and still no luck.

**Comment by kandrei** [comment] 2016-06-02 18:12
@rodaddy : What version are you using?

**Comment by cmgmyr** [comment] 2016-06-02 18:25
I just updated to `1.2.6` from `1.0.0` and with the following config settings, it is working again:

```
{
    "_comments": [
        "Valid terminals include: 'Terminal.app' or 'iTerm'",
        "In the editor value change 'default' to 'nano', 'vi', or another terminal based editor.",
        "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
        "For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
    ],
    "editor": "default",
    "launch_at_login": false,
    "terminal": "iTerm",
    "iTerm_version": "nightly",
    "default_theme": "Homebrew",
    "open_in": "tab",
    "show_ssh_config_hosts": false,
    "ssh_config_ignore_hosts": [],
    "ssh_config_ignore_keywords": [],
    "hosts": ...
}
```

**Comment by rodaddy** [comment] 2016-06-02 19:09
New version 3.0.0 of iTerm2


On Jun 2, 2016, at 1:12 PM, kandrei <notifications@github.com> wrote:

@rodaddy <https://github.com/rodaddy> : What version are you using?

**Comment by skebi69** [comment] 2016-06-02 19:13
@rodaddy - I think he meant what version of Shuttle are you using...

**Comment by kandrei** [comment] 2016-06-02 19:15
Yes, I was asking about the Shuttle version. But according to @cmgmyr, it should work on the 1.2.6 version also, so maybe it's something special with your setup @skebi69 .

**Comment by rodaddy** [comment] 2016-06-02 19:21
Newest 1.2.6. Didn't work with 1.2.5

Cheers,

Rico

Sorry about the short message:
Sent from my iPhone

On Jun 2, 2016, at 2:15 PM, kandrei <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I was asking about the Shuttle version. But according to @cmgmyr<https://github.com/cmgmyr>, it should work on the 1.2.6 version also, so maybe it's something special with your setup @skebi69<https://github.com/skebi69> .

**Comment by patroqueeet** [comment] 2016-06-02 20:02
same for me. changed to 1.2.6 and settings:

```
	"terminal": "iTerm",
    "editor": "default",
    "launch_at_login": false,
    "iTerm_version": "nightly",
    "default_theme": "Default",
    "open_in": "tab",
    "show_ssh_config_hosts": true,
    "ssh_config_ignore_hosts": [],
    "ssh_config_ignore_keywords": [],
```

and its working again

**Comment by euii** [comment] 2016-06-03 02:43
thx @rodaddy it works.

**Comment by thshdw** [comment] 2016-06-03 05:16
Hi All, 
I'm updating to iTerm 3 now and will report back.

**Comment by thshdw** [comment] 2016-06-03 05:44
Hello All, 

I have tested the new nightly ```Build 3.0.20160602-nightly``` and all is working for me with no changes. I'll be on gitter for about 2 or 3 hours so if you need help ping me there. 

Here is the demo config im using:
```
{
  "_comments": [
    "Valid terminals include: 'Terminal.app' or 'iTerm'",
    "In the editor value change 'default' to 'nano', 'vi', or another terminal based editor.",
    "Hosts will also be read from your ~/.ssh/config or /etc/ssh_config file, if available",
    "For more information on how to configure, please see http://fitztrev.github.io/shuttle/"
  ],
  "editor": "default",
  "launch_at_login": false,
  "terminal": "iTerm",
  "iTerm_version": "nightly",
  "default_theme": "Default",
  "open_in": "tab",  
  "show_ssh_config_hosts": false,
  "ssh_config_ignore_hosts": [  ],
  "ssh_config_ignore_keywords": [  ],
  "hosts": [
    {
      "cmd": "ps aux | grep defaults",
      "name": "Grep - Opens in Default-window-theme-title"
    },
    {
      "Spouses Servers": [
        {
          "cmd": "echo '—->WARNING<-- Running a command in this active terminal! Are you sure? y/n'; read sure; if [ $sure == y ]; then echo running command... && tail -f /var/log/current; else echo exiting...; fi",
          "inTerminal": "current",
          "name": "Logs - Opens in the current active terminal window"
        },
        {
          "Jane’s Servers": [
            {
              "cmd": "ssh username@blog2.example.com",
              "inTerminal": "tab",
              "name": "SSH blog - Opens in Tab of active window",
              "theme": "basic",
              "title": "title of tab"
            },
            {
              "cmd": "ssh username@shop1.example.com",
              "inTerminal": "new",
              "name": "SSH Shop - Opens in New Window",
              "theme": "basic",
              "title": "title of new window"
            }
          ]
        }
      ]
    },
    {
      "Vagrant": [
        {
          "cmd": "ssh vagrant@127.0.0.1 -p 2222 -i ~/.vagrant.d/insecure_private_key",
          "name": "Vagrant - Opens in default-window-theme-title"
        }
      ]
    }
  ]
}
```

**Comment by thshdw** [comment] 2016-06-03 05:50
btw.. the gitter link is [here](https://gitter.im/fitztrev/shuttle?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)  :)

**Comment by thshdw** [comment] 2016-06-03 23:58
I'm going to close this. It's hard to know for sure because I dont know what version everyone is upgrading from but shuttle has a lot of new directives. If your shuttle.JSON is not correct its not going to work. Above I posted a working config. If you have questions please let me know.

**Closed by thshdw** 2016-06-03 23:58 UTC

**Comment by BitBrit** [comment] 2016-06-06 18:06
I have the exact same config file as yours (except for the hosts parts) and yet my Shuttle still doesn't work. All it does is focus iTerm but doesn't create a new tab or insert the ssh line. I am using Shuttle 1.2.6. 

Is there anything else I can check?
